---
name: renovate
on:
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  workflow_dispatch:

  push:
    branches: ["main"]
    paths:
      - .github/workflows/renovate.yaml
      - .github/renovate.json
      - renovate.json
      - .github/renovate.json5
      - .github/renovate-config.js
      - .github/renovate/**  # any file in .github/renovate/

jobs:
  run-renovate:
    name: Run Renovate
    runs-on: ubuntu-24.04
    # runs-on: gha-runner-scale-set-zoe-os-verde

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
          repositories: "zoe-os"

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.11
        with:
          # configurationFile: .github/renovate.json
          token: "${{ steps.app-token.outputs.token }}"
